name: casago
description: CasaGo app
publish_to: "none"

version: 1.1.2+48                    

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  url_launcher: ^6.1.11
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^6.1.5
  geolocator: ^13.0.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vehicles/
    - assets/images/casago-logo.png
    - .env


